<?php
/**
* Process text logs generated by File Transport method
* So they can be replayed at the command line
*
* Code quality is very poor and should be rewritten
* Use with extreme caution!
*
* @package Elastica
* @author Eden Akhavi <eden.akhavi@ltt.com>
*/

$arrayBuffer = file("/tmp/elastica.log");

$tempBufferPos=0;
$tempArraySize=sizeof($arrayBuffer);

while ($tempBufferPos<$tempArraySize)
{
	$arrayBuffer[$tempBufferPos]=trim($arrayBuffer[$tempBufferPos]);
	$arrayBuffer[$tempBufferPos]=str_replace("'","",$arrayBuffer[$tempBufferPos]);
	if (substr($arrayBuffer[$tempBufferPos],0,3)=="GET")
	{
                echo "curl -X" . $arrayBuffer[$tempBufferPos] . " -d '\n";
                while ($tempBufferPos<$tempArraySize && substr($arrayBuffer[++$tempBufferPos],0,1)=="{")
                {
			$arrayBuffer[$tempBufferPos]=str_replace("'","",$arrayBuffer[$tempBufferPos]);
                        echo trim($arrayBuffer[$tempBufferPos]);
                }
                echo "'\n";
	}
	else if (substr($arrayBuffer[$tempBufferPos],0,3)=="PUT")
	{
		echo "curl -X" . $arrayBuffer[$tempBufferPos] . " -d '\n";
		while ($tempBufferPos<$tempArraySize && substr($arrayBuffer[++$tempBufferPos],0,1)=="{")
		{
			$arrayBuffer[$tempBufferPos]=str_replace("'","",$arrayBuffer[$tempBufferPos]);
			echo trim($arrayBuffer[$tempBufferPos]);
		}
		echo "'\n";

	}
	else if (substr($arrayBuffer[$tempBufferPos],0,6)=="DELETE")
        {
		echo "curl -X" . $arrayBuffer[$tempBufferPos] . "\n";
		$tempBufferPos=$tempBufferPos+1;
        }
	else
	{
		$tempBufferPos=$tempBufferPos+1;
	}

}

